### PR TITLE
fix hardcoded dbm

### LINKED ISSUE #48: Displays wrong dbm value
image (1)

All of the WLANs are -77dbm, but I’m thinking that they’re not really.
Also, it should be “-77<space>dBm”.

### PR DESCRIPTION
**Pull request by mattludwigs**
closes #48

### CODE REVIEW

File: priv/static/js/access_point.js [hunk 1]
```diff
@@ -73,9 +73,9 @@
     row.setAttribute("data-ssid", ssid);
   }
 
-  function buildSignalTableData({ signal_percent }) {
+  function buildSignalTableData({ signal_percent, signal_dbm }) {
     const tdElem = document.createElement("td");
-    const textNode = document.createTextNode(`${signal_percent}%(-77dbm)`);
+    const textNode = document.createTextNode(`${signal_percent}%(${signal_dbm}dbm)`);
```
Comment (fhunleth) [inline priv/static/js/access_point.js]: Could you add a space between the number and `dBm` (capital B)?
